### ISSUE TITLE
FR13.  Push Notifications

### ISSUE THREAD

**Issue by hkabir2k1** [WSU-4110/Campus-Connects#13]
### Goal

 Allow users to be notified of events.

### Description

Users will be able to choose the option of having a notification. The notification will remind users of pinned events, or if saved events are coming up. 

### Stakeholders

App Server

### Date

9/18/2024

### Version

1.0

### Origin

Identified during initial project discussions about app features and specifications.

### Priority of the proposed feature

Should have

**Comment by brookebui** [comment]
Requires payment

**Comment by brookebui** [comment]
Requires payment
