### ISSUE TITLE
<Clicking on a parking structure 5 crashes the app>

### ISSUE THREAD

**Issue by Ifratt** [WSU-4110/Campus-Connects#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Clicking on a parking structure 5 crashes the app 

### Expected Behavior

When clicking on Parking Structure 5, the app should display its details, such as location, available spaces, and accessibility features, without crashing.

### Steps To Reproduce

Open the app on the desired device.
Navigate to the campus map feature.
Locate and click on Parking Structure 5.
Observe the app crashing.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by brookebui** [comment]
Refined data handling when fetching parking spaces with Google Maps API
